import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://cdn.iconscout.com/icon/premium/png-512-thumb/penis-5157780-4307448.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
